# Generated by Django 4.0 on 2023-05-10 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_usermodel_options_alter_usermodel_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserStateModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('module', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('step', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.usermodel')),
            ],
        ),
    ]
