# Generated by Django 4.0 on 2023-05-10 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userstatemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstatemodel',
            old_name='user_id',
            new_name='user',
        ),
    ]
