# Generated by Django 4.0 on 2023-05-10 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_user_id_userstatemodel_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userstatemodel',
            table='users_state',
        ),
    ]
