# Generated by Django 4.0 on 2023-05-12 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_decisiontreemodel'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='decisiontreemodel',
            table='decision_tree',
        ),
    ]
