# Generated by Django 4.0 on 2023-05-12 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_decisiontreemodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisiontreemodel',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
