# Generated by Django 4.0 on 2023-05-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_decisiontreemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisiontreemodel',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
    ]
