# Generated by Django 4.0 on 2023-05-15 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_decisiontreemodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decisiontreemodel',
            name='instruction',
            field=models.TextField(default=''),
        ),
    ]
