# Generated by Django 4.0 on 2023-06-07 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_decisiontreemodel_instruction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decisiontreemodel',
            options={'verbose_name': 'Decision tree'},
        ),
        migrations.AlterModelOptions(
            name='usermodel',
            options={'verbose_name': 'User'},
        ),
        migrations.AlterModelOptions(
            name='userstatemodel',
            options={'verbose_name': 'User state'},
        ),
    ]
